version: '3'

services:
  web:
    build: .
    command: [ "gunicorn", "wsgi:app", "--bind", "0.0.0.0:3007", "--workers", "3" ]
    ports:
      - "3007:3007"
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: always

  worker:
    build: .
    command: celery -A update worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: always


  beat:
    build: .
    command: celery -A update beat --loglevel=info
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always